/******************************************** 
 * NÁMSKEIÐ ARRAY *
 ******************************************+*/

var namskeidArray = [
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 5,
        month: 'janúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 11,
        month: 'janúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 13,
        month: 'janúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 15,
        month: 'janúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 20,
        month: 'janúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 7,
        month: 'febrúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 17,
        month: 'febrúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 19,
        month: 'febrúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 28,
        month: 'febrúar',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 3,
        month: 'mars',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 12,
        month: 'mars',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 18,
        month: 'mars',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 4,
        month: 'apríl',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 15,
        month: 'apríl',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 30,
        month: 'apríl',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 3,
        month: 'maí',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 12,
        month: 'maí',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 7,
        month: 'júní',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 12,
        month: 'júlí',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 9,
        month: 'ágúst',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 19,
        month: 'ágúst',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 30,
        month: 'ágúst',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 3,
        month: 'september',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 9,
        month: 'september',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 17,
        month: 'september',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 28,
        month: 'september',
        year: 2019,
    }, 
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 11,
        month: 'október',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 14,
        month: 'október',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 16,
        month: 'október',
        year: 2019,
    }, 
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 20,
        month: 'október',
        year: 2019,
    },
    {
        img: 'img/namsk_img02.jpg',
        title: 'Núvitund gegn streitu',
        day: 8,
        month: 'nóvember',
        year: 2019,
    },
    {
        img: 'img/namsk_img01.jpg',
        title: 'Kundalini Grunnnámskeið',
        day: 9,
        month: 'nóvember',
        year: 2019,
    },
    {
        img: 'img/namsk_img03.jpg',
        title: 'Meðgöngujóga',
        day: 5,
        month: 'desember',
        year: 2019,
    }, 
];

